## Basic Configuration

baseurl = "https://shenoybr.github.io/hugo-goa-demo/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Matthew Henderson"
title = "Matthew Henderson"

theme = "hugo-goa"

## Hugo Built-in Features
disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Matthew Henderson"
intro = "Data Scientist"
description = ""
#authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
github = "MHenderson"
#instagram = "<username>"
#xing = "<username>"
linkedin = "<username>"
twitter = "dorsetdata"
#facebook = "<username>"
#google = "<username>"
googlescholar = "<account_id>"
#stackoverflow = "<username>"
#lastfm = "<username>"
goodreads = "<username>"
gitlab = "MHenderson1"
bitbucket = "matthew"
#fivehundredpx = "<username>"
#flickr = "<username>"
#foursquare = "<username>"
#hackernews = "<username>"
#kickstarter = "<username>"
#patreon = "<username>"
#pintrest = "<username>"
#steam = "<username>"
#reddit = "<username>"
#snapchat = "<username>"
#youtube = "<channelid>"
#keybase = "<username>"
#twitch = "<username>"
#soundcloud = "<username>"
#tumblr = "<username>"
#strava = "<username>"
#skype = "<username>"
#telegram = "<username>"
#whatsapp = "<username>"
email = "you@example.com"

## Extras
[params.extra]
copyright = "Â© 2019. Matthew Henderson. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = true
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "coderag"
    identifier = "coderag"
    weight = 300
    url = "/coderag/"
